### ISSUE TITLE
YAML files: improve and add sha256

### ISSUE THREAD

**Issue by tdegeus** [tdegeus/shelephant#113]
The hostinfo should be
```yaml
- root: ...  # was "prefix" before. Can be relative to the file, or absolute (required for remote host)
- files:
  - a.txt
  - b.txt
```
or
```yaml
- root: ...
- files:
  - relpath: a.txt  # must be relative to "root"
    sha256: ...
    created: ... # creation date/time
    modified: ... # modification date/time
    size: ... # size in bytes
  - relpath: b.txt
    sha256: ...
    created: ... # creation date/time
    modified: ... # modification date/time
    size: ... # size in bytes
```
